#!/nix/store/agkxax48k35wdmkhmmija2i2sxg8i7ny-bash-5.2p26/bin/bash

# Can be used as a pre-push hook
# Just symlink this file to .git/hooks/pre-push

echo "Running linter..."
luacheck .

echo "Checking formatting..."
stylua --check .
